# Netlify configuration
[build]
  base = "github-deployment"
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://vasplegalassist.onrender.com/api"
  NODE_VERSION = "18"

# Redirects for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200