[build]
  # Directory to change to before starting a build
  base = "github-deployment"
  
  # Directory that contains the deploy-ready files
  publish = "build"
  
  # Build command
  command = "npm install && npm run build"

[build.environment]
  # Ensure we use a compatible Node version
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200