# Render configuration for backend
services:
  - type: web
    name: vasp-legal-assistant-api
    env: node
    buildCommand: cd github-deployment/backend && npm install && npx prisma generate
    startCommand: cd github-deployment/backend && node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vasp-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://www.theblockrecord.com
      - key: NODE_ENV
        value: production

databases:
  - name: vasp-db
    databaseName: vasp_legal_assistant
    user: vasp_user